### ISSUE TITLE
Migrate webida from http to https only post installation is not documented.

### ISSUE THREAD

**Issue by mukul-git** [webida/webida-server#125]
Can anyone of the contributors guide/suggest simpler way to migrate webida from http to https only configuration ?

**Comment by hwshim** [comment]
@gotchazipc 
Please check this issue.
Thanks.

**Comment by gotchazipc** [comment]
As you see, conf.js is not a simple json file but somewhat complex script producing real configuration values. We highly recommend you copy default-conf.js to conf.js to merge upstream changes. 

If you don't care about internal http connectinons among unit services (fs, auth, ... etc) then just set SSL key & cert file paths in your conf/(default-)conf.js (grep WEBIDA_SSL_(.*)_PATH  to find them) and change  **useSecureProtocol** variable to true in the conf.js. At least, that's what we've done to serve https://webida.org 

If you want to replace all internal connections with SSL/TLS, set 'every' URLs in conf.js using http to https. Then, change conf/routingTable.json file, too. But some modules are using dnode instead of http and cannot be changed. More over, connections to DB server (MySQL) may not be encrypted, too. 

We're changing our configuration file & documentation, moving to webida-server wiki. (current MD files will be removed soon) Since Webida is not production-ready one yet, fill free to ask us anything on configuration and running.

**Comment by kyungmi** [comment]
And you may update `redirect_url` colums data of all system clients in the `oauth_client` table of database.

We are trying to find the way to update configurations more easily.

**Comment by mukul-git** [comment]
For time being I have added an https server for each module, and based on config file entry start either of http or https instance.

**Comment by gotchazipc** [comment]
We may have to lookup proxy unit coces to support SSL termination (that means, we have to proxy https requests to http servers)
