### ISSUE TITLE
Fix error message(Github, Google Login) adding more details.

### ISSUE THREAD

**Issue by kyungmi** [webida/webida-server#179]
When there is not allowed to create new account and a user try to Github/Google login with the new email address, "Internal Server Error" message will be shown on the screen.
It's better to change this message adding more details.

The real error occurs at https://github.com/webida/webida-server/blob/master/src/server/auth/lib/user-manager.js#L248

**Comment by gseok** [comment]
problem

1. There are different error message logic of github and google.
  - https://github.com/webida/webida-server/blob/master/src/server/auth/lib/user-manager.js#L131
  - https://github.com/webida/webida-server/blob/master/src/server/auth/lib/user-manager.js#L248

2. This issue solved When Auth server detached.

-------

we can fix this issue to temp. but there is no significance. so.. I think.. This issue postpone until Auth server detached.

**Comment by gotchazipc** [comment]
we'll discuss on this issue later. just fix ACL table for now.

**Comment by gotchazipc** [comment]
Auth server will not be detached so soon. We may have to fix this error in this sprint using webida.org 

Real problem is we don't have staging server for webida.org yet & it's not a simple job to create a new server for staging, for we need to set DNS records for the staging server (including 10+ domain names)  and to wait for punching a home to incomfing fire-wall. 

I'm not sure we can prepare staging server so fast to fix this issue and we should move to server 2.0 as soon as possible. This issue looks not so complex that we may handle in running webida.org machine.

**Comment by gotchazipc** [comment]
The 'Internal Server Error' message comes from auth.js:104, missing captured error contents, easy to fix.

**Comment by gseok** [comment]
https://github.com/webida/webida-server/pull/194
